### ISSUE TITLE
Mac端打开意外退出

### ISSUE THREAD

**Issue by wisRen** [kevin2li/PDF-Guru#11]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 57CA6429-A273-46D9-85DD-C15BE9AA702A
CrashReporter Key:   8459976F-B334-E42B-0477-43206B3BAB27
Hardware Model:      MacBookPro15,3
Process:             PDF Guru [38683]
Path:                /private/var/folders/*/PDF Guru.app/Contents/MacOS/PDF Guru
Identifier:          com.wails.PDF Guru
Version:             1.0.0 (1.0.0)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.wails.PDF Guru [5549]

Date/Time:           2023-08-03 15:50:41.1973 +0800
Launch Time:         2023-08-03 15:50:41.1104 +0800
OS Version:          macOS 13.3 (22E252)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000000000c8
Exception Codes: 0x0000000000000001, 0x00000000000000c8
VM Region Info: 0xc8 is not in any region.  Bytes before following region: 140737487400760
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7ffffff17000-7ffffff18000 [    4K] r-x/r-x SM=SHM  
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [38683]

Triggered by Thread:  0

Thread 0 Crashed:
0   ???                           	    0x7ff809b01ed4 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x00007ff809b67ec6  rdx: 0x0000000000000000
  rdi: 0x000000000000000f  rsi: 0x000000000000971b  rbp: 0x00007ff7bfeff5b0  rsp: 0x00007ff7bfeff330
   r8: 0x00007ff84d52f0c0   r9: 0x0000000000000170  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x00007ff84b7a0600  r13: 0x0000000009a64000  r14: 0x0000000000000000  r15: 0x00007ff809afc000
  rip: 0x00007ff809b01ed4  rfl: 0x0000000000010246  cr2: 0x00000000000000c8
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Binary Images:
       0x1017c9000 -        0x101864fff  (*) <afa3518c-143e-3060-bbe8-624d4ca41063> ???
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"PDF Guru","timestamp":"2023-08-03 15:50:41.00 +0800","app_version":"1.0.0","slice_uuid":"00000000-0000-0000-0000-000000000000","build_version":"1.0.0","platform":0,"bundleID":"com.wails.PDF Guru","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3 (22E252)","roots_installed":0,"name":"PDF Guru","incident_id":"57CA6429-A273-46D9-85DD-C15BE9AA702A"}
{
  "uptime" : 56000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,3",
  "coalitionID" : 5549,
  "osVersion" : {
    "train" : "macOS 13.3",
    "build" : "22E252",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-03 15:50:41.1973 +0800",
  "incident" : "57CA6429-A273-46D9-85DD-C15BE9AA702A",
  "pid" : 38683,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-03 15:50:41.1104 +0800",
  "procStartAbsTime" : 56128830493362,
  "procExitAbsTime" : 56128916918339,
  "procName" : "PDF Guru",
  "procPath" : "\/private\/var\/folders\/*\/PDF Guru.app\/Contents\/MacOS\/PDF Guru",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0","CFBundleVersion":"1.0.0","CFBundleIdentifier":"com.wails.PDF Guru"},
  "storeInfo" : {"deviceIdentifierForVendor":"4794C209-6599-53F5-A11F-93DA5C0251FA","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.wails.PDF Guru",
  "crashReporterKey" : "8459976F-B334-E42B-0477-43206B3BAB27",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 2083,
  "bridgeVersion" : {"build":"20P4252","train":"7.4"},
  "sleepWakeUUID" : "23D7663F-78C0-4473-98F6-EEEC85A7B8F4",
  "sip" : "enabled",
  "vmRegionInfo" : "0xc8 is not in any region.  Bytes before following region: 140737487400760\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7ffffff17000-7ffffff18000 [    4K] r-x\/r-x SM=SHM  ",
  "exception" : {"codes":"0x0000000000000001, 0x00000000000000c8","rawCodes":[1,200],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000000c8"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":38683},
  "vmregioninfo" : "0xc8 is not in any region.  Bytes before following region: 140737487400760\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7ffffff17000-7ffffff18000 [    4K] r-x\/r-x SM=SHM  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":816355,"instructionState":{"instructionStream":{"bytes":[137,165,120,255,255,255,72,141,5,175,237,162,67,139,56,69,49,228,137,254,49,210,185,255,255,255,255,232,251,155,7,0,72,141,61,37,5,202,65,72,141,117,200,72,141,85,192,232,138,52,2,0,132,192,15,132,243,1,0,0,72,139,93,200,76,141,37,69,231,201,65,73,139,60,36,190,112,1,0,0,232,190,151,7,0,65,137,198,133,192,15,133,118,1,0,0,139,131,200,0,0,0,133,192,116,10,73,139,12,36,137,129,200,0,0,0,72,139,67,16,72,141,149,0,254,255,255,76,137,58,72,141,13,209,23,8,0,233,130,1,0,0,73,139,60,36,232,1,174,4,0,132,192,15,133,100,3,0,0,72,141,61,166,4,202,65,232,133,50,2,0,132,192,15,133,80,3,0,0,76,137,231,232,219,46,0,0,72,141,53,185,23],"offset":96}},"threadState":{"r13":{"value":161890304},"rax":{"value":0},"rflags":{"value":66118},"cpu":{"value":2},"r14":{"value":0},"rsi":{"value":38683},"r8":{"value":140704425898176},"cr2":{"value":200},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":368},"r15":{"value":140703291129856},"rbx":{"value":0},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":582},"rip":{"value":140703291154132,"matchesCrashFrame":1},"rbp":{"value":140702053823920},"rsp":{"value":140702053823280},"r12":{"value":140704394905088},"rcx":{"value":140703291571910},"flavor":"x86_THREAD_STATE","rdi":{"value":15}},"frames":[{"imageOffset":140703291154132,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4319907840,
    "size" : 638976,
    "uuid" : "afa3518c-143e-3060-bbe8-624d4ca41063",
    "name" : ""
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=6064K resident=0K(0%) swapped_out_or_unallocated=6064K(100%)\nWritable regions: Total=9008K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9008K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                       13.6M        4 \nVM_ALLOCATE (reserved)             232K        2         reserved VM address space (unallocated)\n__DATA                              16K        1 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         340K        3 \n__TEXT                            5728K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                             83.8M       17 \nTOTAL, minus reserved VM space    83.6M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "72156cbc4f3e471a1c1cc26e16523e46cbb678ac",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000016
    },
    {
      "treatmentId" : "8ca8349c-e2bc-482c-9ca7-3907b48a5341",
      "experimentId" : "648b5a581b04c12d4127bbb6",
      "deploymentId" : 400000001
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

**Comment by wisRen** [comment]
然后尝试编译
pip install -r requirements.txt 这一步显示都满足了
这一步遇到问题了 pyinstaller -F -w pdf.py

1569 INFO: PyInstaller: 5.13.0
1569 INFO: Python: 3.9.16 (conda)
1583 INFO: Platform: macOS-13.3-x86_64-i386-64bit
2203 INFO: Appending 'binaries' from .spec
2204 INFO: checking Analysis
2204 INFO: Building Analysis because Analysis-00.toc is non existent
2204 INFO: Initializing module dependency graph...
2209 INFO: Caching module graph hooks...
2219 INFO: Analyzing base_library.zip ...
7722 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
10389 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
11092 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
11627 INFO: Caching module dependency graph...
11713 INFO: running Analysis Analysis-00.toc
11717 INFO: Analyzing /Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/pdf.py
12389 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
12672 INFO: Loading module hook 'hook-xml.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
13467 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
13475 INFO: Processing pre-safe import module hook distutils from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-distutils.py'.
13475 INFO: Processing pre-find module path hook distutils from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
14101 INFO: Loading module hook 'hook-distutils.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
14565 INFO: Loading module hook 'hook-PIL.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
14614 INFO: Loading module hook 'hook-PIL.Image.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
16495 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
16625 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
17119 INFO: Loading module hook 'hook-platform.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
17562 INFO: Loading module hook 'hook-pycparser.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
18016 INFO: Loading module hook 'hook-distutils.util.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
18240 INFO: Loading module hook 'hook-setuptools.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
22839 INFO: Loading module hook 'hook-pkg_resources.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
27085 INFO: Loading module hook 'hook-importlib_metadata.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
27595 INFO: Loading module hook 'hook-packaging.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
28698 INFO: Loading module hook 'hook-numpy.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
30794 INFO: Loading module hook 'hook-difflib.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
32287 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
34254 INFO: Loading module hook 'hook-lz4.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
34925 INFO: Loading module hook 'hook-lxml.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37831 INFO: Loading module hook 'hook-reportlab.lib.utils.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
38028 INFO: Loading module hook 'hook-reportlab.pdfbase._fontdata.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
40577 INFO: Loading module hook 'hook-pyphen.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
42027 INFO: Loading module hook 'hook-Crypto.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
42902 INFO: Processing module hooks...
43204 INFO: Processing pre-safe import module hook six.moves from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
44940 INFO: Loading module hook 'hook-charset_normalizer.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
45251 INFO: Loading module hook 'hook-lxml.isoschematron.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
45256 INFO: Loading module hook 'hook-lxml.etree.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
45350 INFO: Processing pre-safe import module hook win32com from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
46785 INFO: Loading module hook 'hook-jinja2.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
47228 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
48879 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks'...
48908 INFO: Loading module hook 'hook-lxml.objectify.py' from '/usr/local/anaconda3/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
48938 INFO: Looking for ctypes DLLs
48961 INFO: Analyzing run-time hooks ...
48968 INFO: Including run-time hook '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_setuptools.py'
48969 INFO: Including run-time hook '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
48970 INFO: Including run-time hook '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
48975 INFO: Including run-time hook '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
48976 INFO: Including run-time hook '/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
49003 INFO: Looking for dynamic libraries
51127 INFO: Looking for eggs
51134 INFO: Python library not among binary dependencies. Performing additional search...
51138 INFO: Using Python library /usr/local/anaconda3/lib/libpython3.9.dylib
51159 INFO: Warnings written to /Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/build/pdf/warn-pdf.txt
51250 INFO: Graph cross-reference written to /Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/build/pdf/xref-pdf.html
51286 INFO: checking PYZ
51286 INFO: Building PYZ because PYZ-00.toc is non existent
51286 INFO: Building PYZ (ZlibArchive) /Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/build/pdf/PYZ-00.pyz
52410 INFO: Building PYZ (ZlibArchive) /Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/build/pdf/PYZ-00.pyz completed successfully.
52431 INFO: EXE target arch: x86_64
52431 INFO: Code signing identity: None
52436 INFO: checking PKG
52436 INFO: Building PKG because PKG-00.toc is non existent
52436 INFO: Building PKG (CArchive) pdf.pkg
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 376, in checkCache
    osxutils.sign_binary(cachedfile, codesign_identity, entitlements_file)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 386, in sign_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '-s', '-', '--force', '--all-architectures', '--timestamp', '/Users/jie/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/lib-dynload/_struct.cpython-39-darwin.so']) failed with error code 109!
output: The following arguments were not expected: --timestamp --all-architectures
Run with --help for more information.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "/Users/jie/bda/270-biotool-install/PDF-Guru/thirdparty/pdf.spec", line 24, in <module>
    exe = EXE(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 572, in __init__
    self.pkg = PKG(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 240, in __init__
    self.__postinit__()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/api.py", line 291, in assemble
    src_name = checkCache(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 395, in checkCache
    raise SystemError(f"Failed to process binary {cachedfile!r}!") from e
SystemError: Failed to process binary '/Users/jie/Library/Application Support/pyinstaller/bincache00_py39_64bit/x86_64/adhoc/no-entitlements/lib-dynload/_struct.cpython-39-darwin.so'!

**Comment by kevin2li** [comment]
Mac端我目前没有测试机器，有条件的可以根据README的编译安装部分自行编译安装
