### ISSUE TITLE
奇偶页合并问题

### ISSUE THREAD

**Issue by wf3699** [kevin2li/PDF-Guru#13]
比如，我用CS扫描王扫描了8个证件的正反面（共16页）
扫描时候证件大致都在上半部分。现在需要将正反面合到一个页面里。可以单独添加一个这样的功能吗？

裁剪全部页面的下半部分，然后拼接成一个页面

**Comment by kevin2li** [comment]
你可以组合现有功能完成，先用裁剪功能把全部页面上半部分和下半部分裁出来，然后使用组合功能每两页合成一页，注意排列顺序
