### ISSUE TITLE
制作双层pdf

### ISSUE THREAD

**Issue by IDKhow2do** [kevin2li/PDF-Guru#29]
: Traceback (most recent call last): File "dual_layer.py", line 15, in make_dual_layer_pdf FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

直接下载的二进制软件，已经配置了如下路径，并下载了中文包（可能是因为通过homebrew安装的缘故？
<img width="549" alt="image" src="https://github.com/kevin2li/PDF-Guru/assets/92859959/3d3085cb-6c88-421c-9b52-228f4e97658a">
<img width="785" alt="image" src="https://github.com/kevin2li/PDF-Guru/assets/92859959/acd77c08-f0a0-4e92-9eda-a42c751a33ba">

**Comment by kevin2li** [comment]
用最新版试试
