### ISSUE TITLE
V1.1.4版本，去除文字水印功能出错

### ISSUE THREAD

**Issue by zhangxq0521** [kevin2li/PDF-Guru#30]
尝试去除文字水印时出错。
![image](https://github.com/kevin2li/PDF-Guru/assets/8443816/89de6c26-f846-4c93-b1c1-e641b9c0d85f)

错误信息如图。
![image](https://github.com/kevin2li/PDF-Guru/assets/8443816/9c7d744a-5bf6-4d47-a16c-dcf6d3c01dc5)

尝试手工安装pdfrw模块后，仍然出错。
![image](https://github.com/kevin2li/PDF-Guru/assets/8443816/502a44a2-8e67-4f48-a29b-270773cbb3e8)

个人猜测，PDF-Guru应用中已经打包了python解释器，不会调用系统提供的Python包。

请帮忙fix这个bug。

**Comment by kevin2li** [comment]
版本没问题，你首选项参数恢复默认试试

**Comment by kevin2li** [comment]
用最新版试试
