### ISSUE TITLE
内容水印步骤一可以正常进行，步骤二不能工作

### ISSUE THREAD

**Issue by Ssspirit** [kevin2li/PDF-Guru#37]
[【精简版】视频课讲义（下）.pdf](https://github.com/kevin2li/PDF-Guru/files/13850242/default.pdf)

直接对大文件进行操作在45秒后会报错。

尝试拆分为1页一个的小文件进行处理，显示处理完成但水印并没有被去除。可是执行步骤一时水印是能去除的。

**Comment by kevin2li** [comment]
用最新版试试
