### ISSUE TITLE
图片转换为pdf报错

### ISSUE THREAD

**Issue by AndreaElijha** [kevin2li/PDF-Guru#38]
使用从飞书下载的二进制版本报错“连接服务器超时”
![4b87f1f23421aa61002a58dbbce9ef7c](https://github.com/kevin2li/PDF-Guru/assets/35521914/228c5beb-9b2a-4129-9008-40a54a68789a)

自己编译的版本python报错
![屏幕截图 2024-01-12 211421](https://github.com/kevin2li/PDF-Guru/assets/35521914/c4d160ac-eff7-4894-9c96-02c97d0e28cc)

内容如下：
: Traceback (most recent call last): File "convert.py", line 158, in convert_svg2pdf new_path_list = sorted(new_path_list, key=lambda x: int(re.search(r"\d+$", Path(x).stem).group())) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "convert.py", line 158, in <lambda> new_path_list = sorted(new_path_list, key=lambda x: int(re.search(r"\d+$", Path(x).stem).group())) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'group'

编译环境：
 Python 3.12.0 in conda  
Windows11
go version go1.21.6 windows/amd64
npm version 10.2.4

**Comment by kevin2li** [comment]
软件免查杀做了吗？软件重装一下，把安装目录添加到杀毒软件信任区

**Comment by AndreaElijha** [comment]
> 软件免查杀做了吗？软件重装一下，把安装目录添加到杀毒软件信任区

免杀做了，mac和Windows上报同样的错。

**Comment by AndreaElijha** [comment]
> 其他功能报错吗
更新了软件版本到1.1.13，之前使用的版本是1.1.10

1.1.13版本其他功能正常使用，但图片转换为pdf功能依然报错，报错内容与自己编译版本相同
\AppData\Local\Temp\_MEI55162\guru_server\pdf_toolbox\convert.py", line 114, in <lambda> AttributeError: 'NoneType' object has no attribute 'group'

1.1.10版本其他功能在win和mac平台均报错，找不到服务器

我是最先在linux上找一个pdf编辑工具，当时的版本是1.1.10，自己编译了在Linux上使用，图片转换pdf和其他功能均正常

**Comment by AndreaElijha** [comment]
> 其他功能报错吗

更新了软件版本到1.1.13，之前使用的版本是1.1.10

1.1.13版本其他功能正常使用，但图片转换为pdf功能依然报错，报错内容与自己编译版本相同
\AppData\Local\Temp_MEI55162\guru_server\pdf_toolbox\convert.py", line 114, in AttributeError: 'NoneType' object has no attribute 'group'

1.1.10版本其他功能在win和mac平台均报错，找不到服务器

我是最先在linux上找一个pdf编辑工具，当时的版本是1.1.10，自己编译了在Linux上使用，图片转换pdf和其他功能均正常

**Comment by kevin2li** [comment]
你转换参数截图看看

**Comment by kevin2li** [comment]
如果你排序方式是编号的话 文件名要用数字结尾，类似xx001.png
