### ISSUE TITLE
建议使用Nuitka打包可执行文件

### ISSUE THREAD

**Issue by lon91ong** [kevin2li/PDF-Guru#4]
打包效果如下：
[参考](https://github.com/Nuitka/Nuitka/issues/1540#issuecomment-1110371392)

![](https://user-images.githubusercontent.com/16462258/165413718-41589caa-35b6-425e-a1a0-eb4e0f622b32.png)

**Comment by kevin2li** [comment]
理由呢 更快的执行速度，还是更小的体积

**Comment by lon91ong** [comment]
> 理由呢 更快的执行速度，还是更小的体积

both，速度和体积兼得

**Comment by kevin2li** [comment]
ok，已采用nuitka
