### ISSUE TITLE
MAC big sur下，用最新版本打开后，没有内容。。。。

### ISSUE THREAD

**Issue by hokhyk** [kevin2li/PDF-Guru#41]
![image](https://github.com/kevin2li/PDF-Guru/assets/12180129/63d730ee-76c8-4780-a030-b2ae2af1d920)
<img width="1291" alt="image" src="https://github.com/kevin2li/PDF-Guru/assets/12180129/23b37949-bddb-4eaf-813e-43448817f817">

**Comment by kevin2li** [comment]
去飞书上下载最新版
