### ISSUE TITLE
使用基于字体属性生成标签的功能时报错

### ISSUE THREAD

**Issue by hijos** [kevin2li/PDF-Guru#45]
报错如下：
处理失败！
: 命令执行失败!2024-03-02 23:41:59.739 | DEBUG | __main__:<module>:399 - Namespace(bookmark_which='detect', input_path='C:\\Users\\ms-ml\\Downloads\\����˼��ʷ һ�������Ե��ӽ� (1).pdf', output=None, page_range='31-N', type='font', which='bookmark') 2024-03-02 23:41:59.746 | ERROR | __main__:<module>:551 - Traceback (most recent call last): File "bookmark.py", line 261, in find_title_by_rect_annot File "fitz\fitz.py", line 7094, in annots File "fitz\fitz.py", line 6400, in load_annot File "fitz\fitz.py", line 6301, in _load_annot RuntimeError: xref 2010 is not an annot of this page During handling of the above exception, another exception occurred: Traceback (most recent call last): File "pdf.py", line 460, in <module> File "bookmark.py", line 379, in find_title_by_rect_annot UnboundLocalError: local variable 'toc' referenced before assignment usage: pdf.exe [-h] {merge,split,delete,insert,replace,rotate,reorder,encrypt,decrypt,change_password,bookmark,watermark,compress,resize,extract,cut,combine,crop,convert,mask,bg,header_footer,page_number,dual,sign,annot} ... positional arguments: {merge,split,delete,insert,replace,rotate,reorder,encrypt,decrypt,change_password,bookmark,watermark,compress,resize,extract,cut,combine,crop,convert,mask,bg,header_footer,page_number,dual,sign,annot} merge �ϲ� split ���� delete ɾ�� insert ���� replace �滻 rotate ��ת reorder ���� encrypt ���� decrypt ���� change_password �޸����� bookmark ��ǩ watermark ˮӡ compress ѹ�� resize ���� extract ��ȡ cut �ָ� combine ���� crop �ü� convert ת�� mask ���� bg ���� header_footer ҳüҳ�� page_number ҳ�� dual ˫��PDF sign ǩ�� annot ��ע optional arguments: -h, --help show this help message and exit : exit status 1

原文件：
[经济思想史 一种批判性的视角 (1)_提取.pdf](https://github.com/kevin2li/PDF-Guru/files/14469911/1._.pdf)

**Comment by kevin2li** [comment]
这个功能对扫描版无效
