### ISSUE TITLE
下载后在内网环境中无法使用软件

### ISSUE THREAD

**Issue by qinxiyan8088** [kevin2li/PDF-Guru#52]
作者您好，我尝试下载了最新的1.1.21以及1.0.12，均无法在离线环境中使用。
安装完毕后点击打开会提示弹窗：
missing requirements
the webView2 runtime needs updating。Press OK to download and install。Note: the installer will download silently so please wait。

但是因为我是内网环境，所以并无外网，点击确定按钮后就没有任何反应了，也没有任何报错信息。
请问有依赖包离线下载导入一下吗？
祝好

**Comment by kevin2li** [comment]
本项目依赖webview2运行环境，你可以去[Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH)选择离线安装包下载安装
