### ISSUE TITLE
请问为什么不换行？

### ISSUE THREAD

**Issue by itangqiao** [kevin2li/PDF-Guru#57]
<img width="853" alt="image" src="https://github.com/user-attachments/assets/5e29278c-e107-4c42-a864-c89f4d25a2e1">

![image](https://github.com/user-attachments/assets/dccd5877-5631-4435-a8db-86b6049dece3)

<img width="791" alt="image" src="https://github.com/user-attachments/assets/d8606e91-0c0d-4193-82fc-7bf887c9578a">

<img width="935" alt="image" src="https://github.com/user-attachments/assets/6663bf4b-03f6-48ce-aa27-6e74d34f2a8e">

**Comment by kevin2li** [comment]
你没有遵循Markdown的换行语法。
https://markdown.com.cn/basic-syntax/line-breaks.html
<img width="798" alt="image" src="https://github.com/user-attachments/assets/107eba1e-071f-41c4-9ff4-bdeae95de2f3">
