### ISSUE TITLE
同时包含文字和图片的pdf，图片中矩形内的批注无法正确遮罩

### ISSUE THREAD

**Issue by Plus-xu** [kevin2li/PDF-Guru#59]
如果pdf中同时含有文字和图片，其中的文字的矩形批注可以正确制卡和遮罩，但是图片的矩形批注只能生成卡片，矩形内的各种批注无法生成遮罩

**Comment by kevin2li** [comment]
请补充截图说明

**Comment by Plus-xu** [comment]
![image](https://github.com/user-attachments/assets/c1a3609d-b7fd-4c6b-be70-048e68bc77fa)
比如这是一个文字和图片混合的pdf中的图片，我在上面花了矩形，里面有黄色批注，生成的anki卡片正反面都是这张图，上面的黄色批注没有遮罩，而pdf中的文字矩形内的批注是可以正常生成遮罩卡片的

**Comment by Plus-xu** [comment]
> 请补充截图说明

![image](https://github.com/user-attachments/assets/c1a3609d-b7fd-4c6b-be70-048e68bc77fa)
比如这是一个文字和图片混合的pdf中的图片，我在上面花了矩形，里面有黄色批注，生成的anki卡片正反面都是这张图，上面的黄色批注没有遮罩，而pdf中的文字矩形内的批注是可以正常生成遮罩卡片的

**Comment by Plus-xu** [comment]
> 请补充截图说明

查看卡片，可以看到Masks字段为空
![image](https://github.com/user-attachments/assets/b0e0e618-b639-4b5b-ac85-67428a8f972f)

**Comment by Plus-xu** [comment]
> 请补充截图说明
![image](https://github.com/user-attachments/assets/f168ebb6-b6db-4a79-9512-1e36fcaf9828)

找到原因了，Guru识别不了adobe acrobat pro（2024最新版）的文本高亮，也就是别的pdf的区域高亮功能。
因为adobe这个所谓的文本高亮也能在图片上高亮，没有单独的区域高亮功能
有什么办法能解决吗？主力是adobe，难道只能换阅读器吗😭

**Comment by kevin2li** [comment]
可以用矩形替代高亮挖空

**Comment by Plus-xu** [comment]
> 可以用矩形替代高亮挖空

解决了感谢
