### ISSUE TITLE
运行报错如下

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [kevin2li/PDF-Guru#6]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 8967D817-8DFD-42F0-A364-621F21C606BE
CrashReporter Key:   A586B257-715A-4D1A-AF67-37857BC12F22
Hardware Model:      MacBookPro15,1
Process:             PDF Guru [26148]
Path:                /private/var/folders/*/PDF Guru.app/Contents/MacOS/PDF Guru
Identifier:          com.wails.PDF Guru
Version:             1.0.0 (1.0.0)
Code Type:           X86-64 (Native)
Role:                Background
Parent Process:      launchd [1]
Coalition:           com.wails.PDF Guru [29067]

Date/Time:           2023-07-26 11:21:43.7193 +0800
Launch Time:         2023-07-26 11:21:40.8308 +0800
OS Version:          macOS 13.4 (22F66)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000000000c8
Exception Codes: 0x0000000000000001, 0x00000000000000c8
VM Region Info: 0xc8 is not in any region.  Bytes before following region: 140737486843704
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffe8f000-7fffffe90000 [    4K] r-x/r-x SM=SHM  
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [26148]

Triggered by Thread:  0

Thread 0 Crashed:
0   ???                           	    0x7ff80cda1ed4 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x00007ff80ce07ec6  rdx: 0x0000000000000000
  rdi: 0x000000000000000f  rsi: 0x0000000000006624  rbp: 0x00007ff7bfeffaf0  rsp: 0x00007ff7bfeff870
   r8: 0x00007ff8507d83c0   r9: 0x0000000000000170  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x00007ff84ea48600  r13: 0x000000000cd04000  r14: 0x0000000000000000  r15: 0x00007ff80cd9c000
  rip: 0x00007ff80cda1ed4  rfl: 0x0000000000010246  cr2: 0x00000000000000c8
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Binary Images:
       0x1017c1000 -        0x10185cfff  (*) <9e98a840-a3ac-31c1-ab97-829af9bd6864> ???
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"PDF Guru","timestamp":"2023-07-26 11:21:43.00 +0800","app_version":"1.0.0","slice_uuid":"00000000-0000-0000-0000-000000000000","build_version":"1.0.0","platform":0,"bundleID":"com.wails.PDF Guru","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"PDF Guru","incident_id":"8967D817-8DFD-42F0-A364-621F21C606BE"}
{
  "uptime" : 140000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,1",
  "coalitionID" : 29067,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-26 11:21:43.7193 +0800",
  "incident" : "8967D817-8DFD-42F0-A364-621F21C606BE",
  "pid" : 26148,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-26 11:21:40.8308 +0800",
  "procStartAbsTime" : 147537764764810,
  "procExitAbsTime" : 147540652778614,
  "procName" : "PDF Guru",
  "procPath" : "\/private\/var\/folders\/*\/PDF Guru.app\/Contents\/MacOS\/PDF Guru",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0","CFBundleVersion":"1.0.0","CFBundleIdentifier":"com.wails.PDF Guru"},
  "storeInfo" : {"deviceIdentifierForVendor":"934931D5-E1C8-51F3-B8A1-4BC58E8B0F3C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.wails.PDF Guru",
  "crashReporterKey" : "A586B257-715A-4D1A-AF67-37857BC12F22",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 4415,
  "bridgeVersion" : {"build":"20P5058","train":"7.5"},
  "sleepWakeUUID" : "9A34525C-0B51-46A5-AD92-5FAC98A5D9FA",
  "sip" : "disabled",
  "vmRegionInfo" : "0xc8 is not in any region.  Bytes before following region: 140737486843704\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7fffffe8f000-7fffffe90000 [    4K] r-x\/r-x SM=SHM  ",
  "exception" : {"codes":"0x0000000000000001, 0x00000000000000c8","rawCodes":[1,200],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000000c8"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":26148},
  "vmregioninfo" : "0xc8 is not in any region.  Bytes before following region: 140737486843704\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7fffffe8f000-7fffffe90000 [    4K] r-x\/r-x SM=SHM  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":1,"thread_set_state":0,"task_for_pid":1},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":3142654,"instructionState":{"instructionStream":{"bytes":[137,165,120,255,255,255,72,141,5,175,128,163,67,139,56,69,49,228,137,254,49,210,185,255,255,255,255,232,251,155,7,0,72,141,61,37,133,202,65,72,141,117,200,72,141,85,192,232,138,52,2,0,132,192,15,132,243,1,0,0,72,139,93,200,76,141,37,69,103,202,65,73,139,60,36,190,112,1,0,0,232,190,151,7,0,65,137,198,133,192,15,133,118,1,0,0,139,131,200,0,0,0,133,192,116,10,73,139,12,36,137,129,200,0,0,0,72,139,67,16,72,141,149,0,254,255,255,76,137,58,72,141,13,17,24,8,0,233,130,1,0,0,73,139,60,36,232,1,174,4,0,132,192,15,133,100,3,0,0,72,141,61,166,132,202,65,232,133,50,2,0,132,192,15,133,80,3,0,0,76,137,231,232,219,46,0,0,72,141,53,249,23],"offset":96}},"threadState":{"r13":{"value":214974464},"rax":{"value":0},"rflags":{"value":66118},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":26148},"r8":{"value":140704479019968},"cr2":{"value":200},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":368},"r15":{"value":140703344214016},"rbx":{"value":0},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":582},"rip":{"value":140703344238292,"matchesCrashFrame":1},"rbp":{"value":140702053825264},"rsp":{"value":140702053824624},"r12":{"value":140704448022016},"rcx":{"value":140703344656070},"flavor":"x86_THREAD_STATE","rdi":{"value":15}},"frames":[{"imageOffset":140703344238292,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4319875072,
    "size" : 638976,
    "uuid" : "9e98a840-a3ac-31c1-ab97-829af9bd6864",
    "name" : ""
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=6056K resident=0K(0%) swapped_out_or_unallocated=6056K(100%)\nWritable regions: Total=9008K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9008K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                       13.6M        4 \nVM_ALLOCATE (reserved)             232K        2         reserved VM address space (unallocated)\n__DATA                              16K        1 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         340K        3 \n__TEXT                            5720K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                             83.8M       17 \nTOTAL, minus reserved VM space    83.6M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "742a70f72b93361e22f26c694248ef784b4c1f50",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000329
    },
    {
      "rolloutId" : "6391cacc75b0720ff1f8c695",
      "factorPackIds" : {
        "COREOS_ICD" : "63957f508061fa721c8edc4a"
      },
      "deploymentId" : 240000007
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro15,1, BootROM 1968.120.12.0.0 (iBridge: 20.16.5058.0.0,0), 6 processors, 6-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: Radeon Pro 555X, Radeon Pro 555X, PCIe, 4 GB
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, HMA81GS6AFR8N-UH
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, HMA81GS6AFR8N-UH
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Dec  9 2022 16:56:24 version 9.30.492.0.32.5.87 FWID 01-3a11ec19
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: iPhone
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Comment by kevin2li** [comment]
Mac端我目前没有测试机器，有条件的可以根据README的编译安装部分自行编译安装

**Comment by landleader** [comment]
![image](https://github.com/kevin2li/PDF-Guru/assets/131670652/1e48758e-a022-4381-91f4-a685bdfc0dfc)

**Comment by landleader** [comment]
页码报错
