### ISSUE TITLE
PDF合并功能报错

### ISSUE THREAD

**Issue by dianjiweiling** [kevin2li/PDF-Guru#7]
: Traceback (most recent call last): File "merge.py", line 34, in merge_pdf File "merge.py", line 34, in <lambda> AttributeError: 'NoneType' object has no attribute 'group'
![image](https://github.com/kevin2li/PDF-Guru/assets/16662089/2cded792-5b15-42d3-acf1-50546897e70a)

**Comment by kevin2li** [comment]
这个要求文件名(不包含后缀)是以数字结尾的格式，例如：test_001.pdf，你的有两个后缀了
